// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl5iyxxQzRI6rXeGlAPu596x0IhOZ4D74',
    appId: '1:42800438877:web:b41a362138d2e08bf377b4',
    messagingSenderId: '42800438877',
    projectId: 'clone-tiktok-pleed0215',
    authDomain: 'clone-tiktok-pleed0215.firebaseapp.com',
    storageBucket: 'clone-tiktok-pleed0215.appspot.com',
    measurementId: 'G-YP6VV2FTGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCksW25a-00_enEU375PUSbrTZ3ACweV8c',
    appId: '1:42800438877:android:dfd29ee8451e50d2f377b4',
    messagingSenderId: '42800438877',
    projectId: 'clone-tiktok-pleed0215',
    storageBucket: 'clone-tiktok-pleed0215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyd8C67f24CFL0YV7Y2a8tWod9k-TYTv0',
    appId: '1:42800438877:ios:e0de8d9afb058044f377b4',
    messagingSenderId: '42800438877',
    projectId: 'clone-tiktok-pleed0215',
    storageBucket: 'clone-tiktok-pleed0215.appspot.com',
    androidClientId: '42800438877-ije5qu03snqb5sdlr4jag5k568hbojoe.apps.googleusercontent.com',
    iosClientId: '42800438877-380pql29ts0nmff9dfantcivt6cng0ml.apps.googleusercontent.com',
    iosBundleId: 'com.pleed0215.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyd8C67f24CFL0YV7Y2a8tWod9k-TYTv0',
    appId: '1:42800438877:ios:d31d44456b13e7bcf377b4',
    messagingSenderId: '42800438877',
    projectId: 'clone-tiktok-pleed0215',
    storageBucket: 'clone-tiktok-pleed0215.appspot.com',
    androidClientId: '42800438877-ije5qu03snqb5sdlr4jag5k568hbojoe.apps.googleusercontent.com',
    iosClientId: '42800438877-g74din4mdbrvpd60le92r4l7jc6sfk1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
